title: Prez js Lengow
email: guillaume@wuips.com
description: ""

baseurl: ""
url: "http://guillaumewuip.github.io/prez-js-lengow"

twitter_username: guillaumewuip
github_username:  guillaumewuip

# Build settings
markdown: kramdown
theme: minima

collections:
- slides

exclude:
- node_modules
- demo

sass:
    sass_dir: css/
